// swift-tools-version:5.9
// SPM manifest for the Swift binding of vf-privacy-kit.
//
// The actual Swift sources are auto-generated by `uniffi-rs` from the
// Rust crate. This package sits in the same repo but is published as a
// standalone SPM artefact at github.com/vfempire-hq/vf-privacy-kit-swift
// (planned) so downstream Swift consumers don't need to clone the Rust
// tree.
//
// See docs/build-bindings.md for how the CI matrix produces the release
// binary + XCFramework + this manifest.

import PackageDescription

let package = Package(
    name: "VFPrivacyKit",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "VFPrivacyKit", targets: ["VFPrivacyKit"]),
    ],
    targets: [
        // In shipping releases, this target is a binaryTarget pointing at
        // the XCFramework built from the Rust crate. Placeholder here.
        .target(
            name: "VFPrivacyKit",
            path: "Sources/VFPrivacyKit",
            swiftSettings: [
                .enableExperimentalFeature("StrictConcurrency"),
            ],
        ),
    ],
)
